#!/bin/bash

echo 'Running tests...'
pytest -v test_*.py --cov-config=.coveragerc --cov=../fpsim --workers auto --durations=0

echo 'Creating HTML report...'
coverage html

echo 'Printing report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"