'''
Simple script to run analyses using the heavy-lifting CalObj class.
'''

import pylab as pl
import calobj as co
import sciris as sc

# Comment/uncomment these to run different analyses
torun = [
#        'loadsave',
        'plot_matrix',
        #'plot_slice',
        ]

filename = 'data/nigeria_cal.obj' # Generated by e.g. sc.saveobj('nigeria_cal.obj', calobj.cal)


sc.tic()


if 'loadsave' in torun:
    print('Loading original data and saving...')
    filename = '/u/cliffk/idm/fp/data/DHS/NGIR6ADT/NGIR6AFL.DTA' # Nigeria 2013 DHS -- warning, system-specific!
    calobj = co.CalObj(filename)
    calobj.save('data/nigeria.cal')
else:
    print('Loading presaved object...')
    #calobj = co.load(filename) # Load saved object
    calobj = co.CalObj(filename) # Create from saved data
   

if 'plot_matrix' in torun:
    calobj.plot_transitions()


if 'plot_slice' in torun:
    calobj.plot_slice(key='None')
    

sc.toc()
print('Done')

pl.show()
