from .kenya import kenya
from .senegal import senegal
from .ethiopia import ethiopia
from .cotedivoire import cotedivoire
from .niger import niger
from .nigeria_kano import nigeria_kano
from .nigeria_kaduna import nigeria_kaduna
from .nigeria_lagos import nigeria_lagos
from .pakistan_sindh import pakistan_sindh
from .ethiopia.regions import addis_ababa
from .ethiopia.regions import afar
from .ethiopia.regions import amhara
from .ethiopia.regions import benishangul_gumuz
from .ethiopia.regions import dire_dawa
from .ethiopia.regions import gambela
from .ethiopia.regions import harari
from .ethiopia.regions import oromia
from .ethiopia.regions import snnpr
from .ethiopia.regions import somali
from .ethiopia.regions import tigray
