from . import kenya
from . import senegal
from . import ethiopia
#adds regions for ethiopia
from .ethiopia_regions import addis_ababa
from .ethiopia_regions import afar
from .ethiopia_regions import amhara
from .ethiopia_regions import benishangul_gumuz
from .ethiopia_regions import dire_dawa
from .ethiopia_regions import gambela
from .ethiopia_regions import harari
from .ethiopia_regions import oromia
from .ethiopia_regions import snnpr
from .ethiopia_regions import somali
from .ethiopia_regions import tigray